- id: kubevious-index-library
  name: kubevious index rules library
  description: Index Kubevious rules library
  types: [file, yaml]
  language: docker_image
  pass_filenames: false
  entry: 'kubevious/cli:1.0.32'
  args: ['index-library', '/src']
- id: kubevious-lint
  name: kubevious lint manifests
  description: Lint Kuberentes manifests
  types: [file, yaml]
  language: docker_image
  pass_filenames: false
  entry: 'kubevious/cli:1.0.32'
  args: ['lint', '/src']
- id: kubevious-guard
  name: kubevious guard manifests
  description: Guard Kuberentes manifests
  types: [file, yaml]
  language: docker_image
  pass_filenames: false
  entry: 'kubevious/cli:1.0.32'
  args: ['guard', '/src']
