- id: kubevious-index-library
  name: kubevious index rules library
  description: Index Kubevious rules library
  types: [file, yaml]
  language: docker_image
  pass_filenames: false
  entry: 'kubevious/cli:1.0.54'
  args: ['index-library', '/src']
- id: kubevious-lint
  name: Kubevious Lint checking for manifest API validity
  description: Kubevious Lint checks for manifest API validity
  types: [file, yaml]
  language: docker_image
  pass_filenames: false
  entry: 'kubevious/cli:1.0.54'
  args: ['lint', '/src']
- id: kubevious-guard
  name: Kubevious Guard checking for manifest validity and violations
  description: Kubevious Guard checks for manifest API validity and violations of best practices
  types: [file, yaml]
  language: docker_image
  pass_filenames: false
  entry: 'kubevious/cli:1.0.54'
  args: ['guard', '/src']
