apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: deployment-env-from-check
spec:
  target: |
    Shortcut("ContainerSpec")  
  rule: |
    for(const envFrom of config.spec.envFrom ?? [])
    {
      if (envFrom.secretRef)
      {
        const secret = Shortcut("Secret", envFrom.secretRef.name)
                          .single();
        
        if (!secret)
        {
          error(`Could not find Secret ${envFrom.secretRef.name}`);
        }
        
      }
    }