apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: certificate-check
spec:
  # disabled: true
  target: |
    ApiVersion('cert-manager.io/v1')
    .Kind('Certificate')
  rule: |
    const issuer = ApiVersion('cert-manager.io/v1')
                .Kind(config.spec?.issuerRef?.kind)
                .name(config.spec?.issuerRef?.name)
                .single();
    if (!issuer) {
      error('Could not find the Certificate Issuer');
    } else {
      const email = issuer.config.spec?.acme?.email ?? "";
      if (!email.endsWith(values.domain)) {
        error(`Using not approved email: ${email}. Should be from ${values.domain} domain.`);
      }
    }
  application:
    useApplicator: true
    onlySelectedNamespaces: true
    namespaces:
      - name: kubevious
        values: 
          domain: kubevious.io
      - name: pepsi
      - name: foo
  values:
    domain: example.com