apiVersion: kubevious.io/v1alpha1
kind: Rule
metadata:
  name: replica-count-check
  namespace: ordering
spec:
  values:
    minReplicas: 1
  target: |
    ApiVersion('apps/v1')
    .Kind('Deployment')
  rule: |
    const hpa = findHPA();
    if (hpa) {
      if (hpa.config.spec.minReplicas <= values.minReplicas)
      {
        error(`HPA minReplicas count should be more than ${values.minReplicas}`);
        return;
      }
    }

    const replicas = config.spec?.replicas ?? 1;
    if (replicas <= values.minReplicas)
    {
      error(`Deployment replica count should be more than ${values.minReplicas}`);
    }
    
    function findHPA()
    {
      for(const hpa of ApiVersion('autoscaling/v2')
                        .Kind('HorizontalPodAutoscaler')
                        .many())
      {
        if (hpa.config?.spec?.scaleTargetRef.kind === 'Deployment' && 
            hpa.config?.spec?.scaleTargetRef.name === config.metadata.name)
        {
          return hpa;
        }        
      }
      return null;
    }