apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: service-selector-v2
spec:
  target: |
    Union(
      ApiVersion('v1')
        .Kind('Service')
    )
  cache: |
    cache.apps = [];

    const items = 
      Union(
        ApiVersion('apps/v1')
          .Kind("Deployment")
      )
      .many()
      ;

    for(const app of items)
    {
      cache.apps.push({
        kind: app.kind,
        name: app.name,
        labels: app.config.spec.template.metadata.labels ?? {}
      });
    }
  rule: |
    if (!config.spec.selector) {
      return;
    }

    for(const app of cache.apps)
    {
      if (matchesDict(config.spec.selector, app.labels))
      {
        return;  
      }
    }

    error("Could not find Applications for Service");

    function matchesDict(selector, labels)
    {
        for(const key of Object.keys(selector))
        {
            if (selector[key] !== labels[key])
            {
                return false;
            }
        }
        return true;
    }