apiVersion: v1
kind: Service
metadata:
  labels:
    app: emailservice
  name: emailservice-1
spec:
  type: ClusterIP
  ports:
  - name: "my-port-is-not-set"
    targetPort: 5432
  selector:
    app: emailservice
  
