---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-pepsi
  namespace: pepsi
spec:
  dnsNames:
    - nonpresent.kubevious.io
  issuerRef:
    kind: ClusterIssuer
    name: pepsi-issuer
    group: cert-manager.io
  secretName: demo-kubevious-tls

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: pepsi-issuer
spec:
  acme:
    email: foo@bar.com
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
    preferredChain: ''
    privateKeySecretRef:
      name: letsencrypt
