apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: emailservice
  namespace: pepsi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emailservice
  minReplicas: 2
  maxReplicas: 24
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: ContainerResource
    containerResource:
      name: cpu
      container: server
      target:
        type: Utilization
        averageUtilization: 60