apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: libraries.kubevious.io
spec:
  group: kubevious.io
  scope: Cluster
  names:
    plural: libraries
    singular: library
    kind: Library
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                rules:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      path:
                        type: string
                      category:
                        type: string
                      summary:
                        type: string
                    required:
                      - name
                      - path
              required:
                - rules
          required:
            - spec