apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ruleapplicators.kubevious.io
spec:
  group: kubevious.io
  scope: Namespaced
  names:
    plural: ruleapplicators
    singular: ruleapplicator
    kind: RuleApplicator
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clusterRuleRef:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                    - name
                disabled:
                  type: boolean
                values:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              required:
                - clusterRuleRef
          required:
            - spec