apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-1
  namespace: argo-test
  labels:
    app: app-1
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: app-1
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 5m}
      - analysis:
          templates:
          - templateName: not-found-percentage
          args:
          - name: service-name
            value: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: node
        image: sckmkny/app-1:0.2.0
        ports:
        - name: node
          containerPort: 3000
